In [23]:
import pandas as pd 
import numpy as np 
from collections import Counter
from legend import MONRACE,RACE2MONRACE,STATES

# Loading in exonerations

In [22]:
exonerations_df = pd.read_excel('data/publicspreadsheet.xlsx',dtype=str)
convictions_df = pd.read_csv('data/2018cirme.csv',dtype=str)

In [3]:
display(exonerations_df)
display(convictions_df)

,Last Name,First Name,Age,Race,Sex,State,County,Tags,Worst Crime Display,List Add'l Crimes Recode,...,DNA,*,FC,MWID,F/MFE,P/FA,OM,ILD,Posting Date,ID
0,Abbitt,Joseph Lamont,31,Black,Male,North Carolina,Forsyth,CV;#IO,Child Sex Abuse,Sexual Assault;#Kidnapping;#Burglary/Unlawful ...,...,DNA,NaN,NaN,MWID,NaN,NaN,NaN,NaN,2011-09-01 00:00:00,3807
1,Abdal,Warith Habib,43,Black,Male,New York,Erie,IO,Sexual Assault,Robbery,...,DNA,NaN,NaN,MWID,F/MFE,NaN,OM,NaN,2011-08-29 00:00:00,2978
2,Abernathy,Christopher,17,White,Male,Illinois,Cook,CIU;#CV;#H;#IO,Murder,Rape;#Robbery,...,DNA,NaN,FC,NaN,NaN,P/FA,OM,NaN,2015-02-13 00:00:00,4640
3,Abney,Quentin,32,Black,Male,New York,New York,CV,Robbery,NaN,...,NaN,NaN,NaN,MWID,NaN,NaN,NaN,NaN,2019-05-13 00:00:00,5553
4,Acero,Longino,35,Hispanic,Male,California,Santa Clara,NC;#P,Sex Offender Registration,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ILD,2011-08-29 00:00:00,2979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2510,Zawacki,Richard,38,White,Male,Indiana,Huntington,CV;#NC,Child Sex Abuse,NaN,...,NaN,NaN,NaN,NaN,NaN,P/FA,NaN,NaN,2017-08-08 00:00:00,5177
2511,Zimmer,Walter,40,White,Male,Ohio,Cuyahoga,CDC;#H;#IO,Manslaughter,Attempted Murder;#Robbery;#Assault;#Kidnapping...,...,DNA,*,NaN,NaN,F/MFE,P/FA,OM,NaN,2013-10-04 00:00:00,4283
2512,Zimmerman,Evan,53,White,Male,Wisconsin,Dodge,H;#IO,Murder,NaN,...,DNA,*,FC,NaN,NaN,NaN,NaN,ILD,2011-08-29 00:00:00,3775
2513,Zinkiewicz,Tyrone,38,White,Male,Ohio,Montgomery,CV;#NC,Other Nonviolent Felony,NaN,...,NaN,NaN,NaN,NaN,NaN,P/FA,OM,NaN,2014-10-25 00:00:00,4521
2514,Zomber,Michael,53,White,Male,Fed-PA,(Eastern),FED,Fraud,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,OM,NaN,2011-08-29 00:00:00,3776

,POOFFICE,ZONE,SORGDL,DESCRIP1,DESCRIP2,DESCRIP3,DESCRIP4,DESCRIP5,DESCRIP6,DESCRIP7,...,RETEXT28,RETEXT29,RETEXT30,RETEXT31,RETEXT32,RETEXT33,RETEXT34,RETEXT35,PCNTDEPT,MNTHDEPT
0,3,D,,,,,,,,,...,,,,,,,,,8.51063829787234,16
1,2,A,,,,,,,,,...,,,,,,,,,,
2,1,C,,,,,,,,,...,,,,,,,,,40,4
3,2,B,,,,,,,,,...,,,,,,,,,50,4
4,1,A,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11459,4,B,,,,,,,,,...,,,,,,,,,99.5,5.97
11460,3,D,,,,,,,,,...,,,,,,,,,48.5714285714286,34
11461,1,D,,,,,,,,,...,,,,,,,,,41.7218543046358,63
11462,2,C,,,,,,,,,...,,,,,,,,,40,4
11463,3,D,,,,,,,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Preprocessing dataframes

## 1. Remove non 2018 exonerations
The exoneration data is for all years, so lets remove all entries that were outside of 2018

In [21]:
exonerations_df.query("Exonerated == '2018'")

,Last Name,First Name,Age,Race,Sex,State,County,Tags,Worst Crime Display,List Add'l Crimes Recode,...,DNA,*,FC,MWID,F/MFE,P/FA,OM,ILD,Posting Date,ID
23,Aguirre-Jarquin,Clemente,24,Hispanic,Male,Florida,Seminole,H;#IO,Murder,Burglary/Unlawful Entry,...,DNA,NaN,NaN,NaN,F/MFE,P/FA,NaN,ILD,2018-11-11 00:00:00,5406
24,Ahmed,Mubarez,31,Other,Male,Michigan,Wayne,CIU;#H;#IO,Murder,Illegal Use of a Weapon,...,NaN,NaN,NaN,NaN,NaN,P/FA,OM,ILD,2018-10-31 00:00:00,5403
34,Alexander,Malcolm,19,Black,Male,Louisiana,Jefferson,IO,Sexual Assault,NaN,...,DNA,*,NaN,MWID,NaN,P/FA,OM,ILD,2018-02-06 00:00:00,5274
44,Allen,Landon,29,Black,Male,Illinois,Cook,CIU;#IO;#NC;#P,Drug Possession or Sale,NaN,...,NaN,NaN,NaN,NaN,NaN,P/FA,OM,NaN,2018-12-09 00:00:00,5446
47,Almond,George,28,Black,Male,Illinois,Cook,CIU;#IO;#NC;#P,Drug Possession or Sale,NaN,...,NaN,NaN,NaN,NaN,NaN,P/FA,OM,NaN,2018-12-09 00:00:00,5440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2440,Williams,Shawn,19,Black,Male,New York,Kings,CIU;#H,Murder,NaN,...,NaN,NaN,NaN,NaN,NaN,P/FA,OM,ILD,2018-07-24 00:00:00,5358
2447,Willis,Deon,33,Black,Male,Illinois,Cook,CIU;#IO;#NC;#P,Drug Possession or Sale,NaN,...,NaN,NaN,NaN,NaN,NaN,P/FA,OM,ILD,2018-12-03 00:00:00,5432
2470,Winston,Michael,29,Black,Male,Wisconsin,Milwaukee,CDC,Attempted Murder,Robbery;#Assault;#Kidnapping,...,NaN,NaN,NaN,MWID,NaN,P/FA,NaN,ILD,2018-09-21 00:00:00,5377
2472,Wise,Martez,23,Black,Male,Illinois,Cook,CIU;#IO;#NC;#P,Drug Possession or Sale,NaN,...,NaN,NaN,NaN,NaN,NaN,P/FA,OM,NaN,2018-12-03 00:00:00,5433
2496,Wurdemann,John,29,Native American,Male,Idaho,Canyon,A;#CDC,Attempted Murder,Robbery;#Assault;#Kidnapping;#Conspiracy,...,NaN,NaN,NaN,MWID,NaN,P/FA,OM,ILD,2018-10-02 00:00:00,5378

In [25]:
# exonerations_df['State'] = exonerations_df['State']\
#                             .replace(STATES)\
#                             .where(exonerations_df['State'][-3:] in STATES.keys(), exonerations_df['State'])

exonerations_df.update(exonerations_df['State'][exonerations_df['State'][-3:] in STATES.keys()].replace(STATES))


for k, v in STATES.items():
    exonerations_df['Place'] = np.where(exonerations_df['Place'].str.contains(k, case=False), v, exonerations_df['Place'])

TypeError: unhashable type: 'Series'

In [20]:
exonerations_df

,Last Name,First Name,Age,Race,Sex,State,County,Tags,Worst Crime Display,List Add'l Crimes Recode,...,DNA,*,FC,MWID,F/MFE,P/FA,OM,ILD,Posting Date,ID
0,Abbitt,Joseph Lamont,31,Black,Male,North Carolina,Forsyth,CV;#IO,Child Sex Abuse,Sexual Assault;#Kidnapping;#Burglary/Unlawful ...,...,DNA,NaN,NaN,MWID,NaN,NaN,NaN,NaN,2011-09-01 00:00:00,3807
1,Abdal,Warith Habib,43,Black,Male,New York,Erie,IO,Sexual Assault,Robbery,...,DNA,NaN,NaN,MWID,F/MFE,NaN,OM,NaN,2011-08-29 00:00:00,2978
2,Abernathy,Christopher,17,White,Male,Illinois,Cook,CIU;#CV;#H;#IO,Murder,Rape;#Robbery,...,DNA,NaN,FC,NaN,NaN,P/FA,OM,NaN,2015-02-13 00:00:00,4640
3,Abney,Quentin,32,Black,Male,New York,New York,CV,Robbery,NaN,...,NaN,NaN,NaN,MWID,NaN,NaN,NaN,NaN,2019-05-13 00:00:00,5553
4,Acero,Longino,35,Hispanic,Male,California,Santa Clara,NC;#P,Sex Offender Registration,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ILD,2011-08-29 00:00:00,2979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2510,Zawacki,Richard,38,White,Male,Indiana,Huntington,CV;#NC,Child Sex Abuse,NaN,...,NaN,NaN,NaN,NaN,NaN,P/FA,NaN,NaN,2017-08-08 00:00:00,5177
2511,Zimmer,Walter,40,White,Male,Ohio,Cuyahoga,CDC;#H;#IO,Manslaughter,Attempted Murder;#Robbery;#Assault;#Kidnapping...,...,DNA,*,NaN,NaN,F/MFE,P/FA,OM,NaN,2013-10-04 00:00:00,4283
2512,Zimmerman,Evan,53,White,Male,Wisconsin,Dodge,H;#IO,Murder,NaN,...,DNA,*,FC,NaN,NaN,NaN,NaN,ILD,2011-08-29 00:00:00,3775
2513,Zinkiewicz,Tyrone,38,White,Male,Ohio,Montgomery,CV;#NC,Other Nonviolent Felony,NaN,...,NaN,NaN,NaN,NaN,NaN,P/FA,OM,NaN,2014-10-25 00:00:00,4521
2514,Zomber,Michael,53,White,Male,penis,(Eastern),FED,Fraud,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,OM,NaN,2011-08-29 00:00:00,3776

In [22]:
newrace_counter = Counter(crime['NEWRACE'])

In [25]:

Counter(crime.query('HISPORIG == 2')['MONRACE'])

Counter({1: 5854, 2: 122, 7: 23, 4: 7, 3: 7, 8: 19, 5: 2, 9: 1})

In [26]:
# replace race of hispanics to be 11 (hisp), since exonerated data considers hispanics to be a race    
crime.loc[crime['HISPORIG'] ==1,'MONRACE'] = 11

In [27]:
Counter(crime['MONRACE'])

Counter({11: 5113, 1: 5994, 2: 180, 4: 12, 8: 123, 7: 24, 3: 14, 5: 3, 9: 1})

In [30]:
new_race = ex.replace({'race':RACE2MONRACE})

In [37]:
sum(Counter(new_race['race']).values())

2515

In [10]:
from geopy.geocoders import Nominatim

In [14]:
loc = Nominatim(user_agent="GetLoc")
getLoc = loc.geocode("Florida	Seminole")
print(getLoc.latitude,getLoc.longitude)

28.7225829 -81.2353683

27.7567667 -81.4639835